source:      .
destination: ./_site
plugins:     ./_plugins

uto:      false
server:   false
lsi:      false
safe:     false
pygments: true
markdown: maruku

permalink: pretty
title:     Ruth and Josh.net
#url:       http://ruthandjosh.net