source:      .
destination: ./_site
plugins:     ./_plugins

uto:      false
server:   false
lsi:      false
safe:     false
pygments: true
markdown: maruku

permalink: pretty
title:     Ruth and Josh.net
#url:       http://ruthandjosh.net

navigation:
- text: Home
  url: /
- text: Story
  url: /story/
- text: Wedding
  url: /wedding/
- text: Hotels
  url: /hotels/
- text: RSVP
  url: /rsvp/
- text: Registry
  url: /registry/
- text: Blog
  url: /blog/