source:      .
destination: ./_site

uto:      false
lsi:      false
safe:     false
markdown: kramdown

permalink: pretty
title:     Ruth and Josh.net
#url:       http://ruthandjosh.net

navigation:
- text: Home
  url: /
- text: Story
  url: /story/
- text: Ceremony
  url: /wedding/
- text: Guests
  url: /guests/
- text: FAQ
  url: /faq/
- text: Registry
  url: /registry/
- text: Blog
  url: /blog/